[canonical_network]
type = "evm"
name = "Ethereum Mainnet"
world_id_addr = "0xf7134CE138832c1456F2a91D64621eE90c2bddEa"
provider = { rpc_endpoint = "https://eth.llamarpc.com" }
wallet = { type = "mnemonic", mnemonic = "your mnemonic here" }

[[bridged_networks]]
type = "evm"
name = "World Chain Mainnet"
address = "0xf7134CE138832c146F2a91D64621eE90c2bddEa"
state_bridge_addr = "0x4c175eE61C3c1da847E339e1158D61BBd2537046"
world_id_addr = "0x047eE5313F98E26Cc8177fA38877cB36292D2364"
provider = { rpc_endpoint = "https://eth.llamarpc.com" }
wallet = { type = "mnemonic", mnemonic = "your mnemonic here" }

[[bridged_networks]]
type = "evm"
name = "Optimism Mainnet"
address = "0xf7134CE138832c1456F2a91D64621eE90c2bddEa"
state_bridge_addr = "0xa6d85F3b3bE6Ff6DC52C3aaBe9A35d0ce252b79F"
world_id_addr = "0xB3E7771a6e2d7DD8C0666042B7a07C39b938eb7d"
provider = { rpc_endpoint = "https://eth.llamarpc.com" }
wallet = { type = "mnemonic", mnemonic = "your mnemonic here" }

[[bridged_networks]]
type = "evm"
name = "Polygon Mainnet"
address = "0xf7134CE138832c1456F2a91D64621eE90c2bddEa"
state_bridge_addr = "0x76Db75dc752305E2deBd44c479680352F3Bb766f"
world_id_addr = "0xa6d85F3b3bE6Ff6DC52C3aaBe9A35d0ce252b79F"
provider = { rpc_endpoint = "https://eth.llamarpc.com" }
wallet = { type = "mnemonic", mnemonic = "your mnemonic here" }
